[package]
name = "veyak"
version = "0.5.1"
description = "A Tauri App"
authors = ["Hrithik Dhakrey <dhakreyhrithik@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "veyak_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
veyak-models = {path= "../crates/veyak-models"}
veyak-error = {path= "../crates/veyak-error"}
veyak-db = {path= "../crates/veyak-db"}
veyak-auth = {path= "../crates/veyak-auth"}
veyak-grpc = {path= "../crates/veyak-grpc"}
veyak-graphql = {path= "../crates/veyak-graphql"}
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-oauth = "2"
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
reqwest = { version = "0.13.4", features = ["json", "multipart", "query", "form", "native-tls"] }
tokio = { workspace = true, features = ["full"] }
uuid = { version = "1.23.3", features = ["v4"] }
url = "2.5.8"
thiserror = "2.0.18"
chrono = "0.4.45"
tokio-tungstenite = { version = "0.30.0", features = ["rustls-tls-native-roots"] }
futures-util = "0.3"
http = "1"
rustls = "0.23.43"
tauri-plugin-dialog = "2.7.2"
tauri-plugin-process = "2.3.1"
tauri-plugin-store = "2.4.4"
rand = "0.10.2"
sha2 = "0.11.0"
base64 = "0.23.1"
urlencoding = "2.1.3"
font-kit = "0.14.3"
tokio-util = "0.7.19"


[features]
default = []
scripting = []

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-updater = "2.10.1"

[dev-dependencies]
glib = "0.20.0"
