[package]
name = "veyak-db"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml = "0.9.34"
uuid = { version = "1.24.1", features = ["v4"] }
veyak-models = {path= "../veyak-models"}
veyak-error = {path= "../veyak-error"}
